/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecthomeoracledb;

import io.netty.util.internal.StringUtil;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

/**
 *
 * @author Deval Nayak
 */
public class KHATADetails extends javax.swing.JFrame {

    /**
     * Creates new form KHATADetails
     */
    public KHATADetails() {
        initComponents();
        System.setProperty("webdriver.chrome.driver", "C:\\CHROMEDRIVERS\\chromedriver-win64_140\\chromedriver.exe");  
        FillCombokhata();
        FillCombokhatasurveyno();
        FillMAPS();
        close();
       
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBKhata = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        khatanum = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ANYRORWEBSITE = new javax.swing.JButton();
        village = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seleddrno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CBsurveyno = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        VillageMAP = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        CBOLDSURVEY = new javax.swing.JComboBox<>();
        GETOLD = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHATA DETAILS");

        CBKhata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKhataActionPerformed(evt);
            }
        });

        jButton1.setText("GET 8A KHATA DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        khatanum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khatanumActionPerformed(evt);
            }
        });

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ANYRORWEBSITE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANYRORWEBSITE.setText("ANYRORWEBSITE");
        ANYRORWEBSITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANYRORWEBSITEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("KHATA NO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("VILLAGE :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SELEDDRNO");

        jButton3.setText("GET 7 DETAILS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CBsurveyno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBsurveynoActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("ALL KHATA SURVEY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        VillageMAP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VillageMAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VillageMAPActionPerformed(evt);
            }
        });

        jButton5.setText("OPEN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("OPENFOLDER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("IORA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("SORT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        CBOLDSURVEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOLDSURVEYActionPerformed(evt);
            }
        });

        GETOLD.setText("GET OLD 7/12");
        GETOLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETOLDActionPerformed(evt);
            }
        });

        jButton9.setText("E-CHAVDI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("REFRESH");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(371, 371, 371)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(village)
                                .addComponent(khatanum)
                                .addComponent(seleddrno, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(CBKhata, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(CBsurveyno, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBOLDSURVEY, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GETOLD, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ANYRORWEBSITE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(VillageMAP, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(khatanum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(village, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seleddrno, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ANYRORWEBSITE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(VillageMAP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBKhata, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBsurveyno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CBOLDSURVEY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(GETOLD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        WebDriver wb=new ChromeDriver();
          JavascriptExecutor jse = (JavascriptExecutor) wb;          
          DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("ANYROR");
          String khata=CBKhata.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 wb.navigate().to(Slink);
         wb.manage().window().maximize();
    	 Thread.sleep(250);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_drpLandRecord"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(6);
         wb.navigate().refresh();
         Thread.sleep(250);
        
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(250);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_ddlDistrict"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         wb.navigate().refresh();
         Thread.sleep(250);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ContentPlaceHolder1_ddlTaluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              wb.navigate().refresh();
              Thread.sleep(250);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ContentPlaceHolder1_ddlVillage"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            wb.navigate().refresh();
            Thread.sleep(250);
            wb.findElement(By.id("ContentPlaceHolder1_txtNo")).sendKeys(ar[0]);
            Thread.sleep(250);
             jse.executeScript("window.scrollBy(0,250)", "");
           }catch(Exception e){
              System.out.println(e.getMessage());
         }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void khatanumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khatanumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khatanumActionPerformed

    private void ANYRORWEBSITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANYRORWEBSITEActionPerformed
         WebDriver wb=new ChromeDriver();
        
          DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("ANYROR");
          
      try { 
    	 wb.navigate().to(Slink);
    	 Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_ddlDistrict"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         wb.navigate().refresh();
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ContentPlaceHolder1_ddlTaluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              wb.navigate().refresh();
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ContentPlaceHolder1_ddlVillage"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(42);
            wb.navigate().refresh();
            Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
    }//GEN-LAST:event_ANYRORWEBSITEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       DBFunctionInterface dbinkhvl=new Insertdata();
       int khatanumb=Integer.parseInt(khatanum.getText());
       String vill=village.getText();
       int seleddrnoa=Integer.parseInt(seleddrno.getText());
       dbinkhvl.insertkhatavillage(khatanumb,vill,seleddrnoa);
       
       khatanum.setText("");
       village.setText("");
       seleddrno.setText("");
       JOptionPane.showMessageDialog(rootPane, "KHATANO DETAILS REGISTERED");
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          WebDriver wb=new ChromeDriver();
          JavascriptExecutor jse = (JavascriptExecutor) wb;          
          DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("ANYROR");
          String khata=CBsurveyno.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 wb.navigate().to(Slink);
         wb.manage().window().maximize();
    	 Thread.sleep(500);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_drpLandRecord"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(5);
         wb.navigate().refresh();
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(500);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_ddlDistrict"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         wb.navigate().refresh();
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ContentPlaceHolder1_ddlTaluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              wb.navigate().refresh();
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ContentPlaceHolder1_ddlVillage"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            wb.navigate().refresh();
            Thread.sleep(500);
            wb.findElement(By.id("ContentPlaceHolder1_txtNo")).sendKeys(ar[0]);
            Thread.sleep(500);
             }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
           WebElement surveyno=wb.findElement(By.id("ContentPlaceHolder1_ddlSurveyNo"));
            Select objsurvey=new Select(surveyno);
            String checksurveyno=CBsurveyno.getSelectedItem().toString();
            String arr[]=checksurveyno.split("-");
            int arlen=arr.length;
            String str=arr[arlen-1];
            objsurvey.selectByValue(str);
            Thread.sleep(500);  
            jse.executeScript("window.scrollBy(0,250)", "");
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ALLKhataSurevyCon aks=new ALLKhataSurevyCon();
        aks.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VillageMAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VillageMAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VillageMAPActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Desktop desktop = Desktop.getDesktop();
       String Village=VillageMAP.getSelectedItem().toString();
       String DLRMAPS="C:\\DLRMAPS\\"+Village;
       File dirToOpen = null;
       try {
            dirToOpen = new File(DLRMAPS);
           try {
               desktop.open(dirToOpen);
           } catch (IOException ex) {
               Logger.getLogger(DocumentsFolders.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (IllegalArgumentException iae) {
            System.out.println("File Not Found");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CBKhataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKhataActionPerformed
//        String getkhata=CBKhata.getSelectedItem().toString();
//        String arr[]=getkhata.split("-");
//        FillCombokhatasurveyno(Integer.parseInt(arr[0])); 
    }//GEN-LAST:event_CBKhataActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Desktop desktop = Desktop.getDesktop();
       String DLRMAPS="C:\\DLRMAPS";
       File dirToOpen = null;
       try {
            dirToOpen = new File(DLRMAPS);
           try {
               desktop.open(dirToOpen);
           } catch (IOException ex) {
               Logger.getLogger(DocumentsFolders.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (IllegalArgumentException iae) {
            System.out.println("File Not Found");
        }        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        KHATADetailsIORA KIORA=new KHATADetailsIORA();
        KIORA.show();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       String Filetosort="C:\\DLRMAPS";
       File fts=new File(Filetosort);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void GETOLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETOLDActionPerformed
        WebDriver wb=new ChromeDriver();
        
          DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("ANYROR");
           String khata=CBsurveyno.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          try { 
    	 wb.navigate().to(Slink);
         wb.manage().window().maximize();
    	 Thread.sleep(250);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_drpLandRecord"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(3);
//         wb.navigate().refresh();
         Thread.sleep(250);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       } 
      try { 
    	 
    
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_ddlDistrict"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
//         wb.navigate().refresh();
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ContentPlaceHolder1_ddlTaluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              wb.navigate().refresh();
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ContentPlaceHolder1_ddlVillage"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
//            wb.navigate().refresh();
            Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }      
    }//GEN-LAST:event_GETOLDActionPerformed

    private void CBOLDSURVEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOLDSURVEYActionPerformed
         
    }//GEN-LAST:event_CBOLDSURVEYActionPerformed

    private void CBsurveynoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBsurveynoActionPerformed
       String NewSurvey=CBsurveyno.getSelectedItem().toString();
       String arr[]=NewSurvey.split("-");
       FillCombokhatasurveyold(Integer.parseInt(arr[2]),arr[1].toString());
    }//GEN-LAST:event_CBsurveynoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       WebDriver wb=new ChromeDriver();
          JavascriptExecutor jse = (JavascriptExecutor) wb;          
          DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("ANYROR");
          String khata=CBKhata.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 wb.navigate().to(Slink);
         wb.manage().window().maximize();
    	 Thread.sleep(250);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_drpLandRecord"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(1);
         wb.navigate().refresh();
         Thread.sleep(250);
        
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(250);
         WebElement district=wb.findElement(By.id("ContentPlaceHolder1_ddlDistrict"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         wb.navigate().refresh();
         Thread.sleep(250);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ContentPlaceHolder1_ddlTaluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              wb.navigate().refresh();
              Thread.sleep(250);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ContentPlaceHolder1_ddlVillage"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            wb.navigate().refresh();
            Thread.sleep(250);
            wb.findElement(By.id("ContentPlaceHolder1_txtNo")).sendKeys(ar[0]);
            Thread.sleep(250);
             jse.executeScript("window.scrollBy(0,250)", "");
           }catch(Exception e){
              System.out.println(e.getMessage());
         }  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       dispose();
       KHATADetails kh=new KHATADetails();
       kh.show();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void FillCombokhata(){
    String Villagenam=null; 
    int khatanu;
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from khatano";
            ResultSet rs=st.executeQuery(qr);
            CBKhata.removeAllItems();
            while(rs.next()){
            khatanu=rs.getInt("khatano");
            Villagenam=rs.getString("village");
            CBKhata.addItem(khatanu+"-"+Villagenam);
            }
          cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
         }
       
}
     private void FillCombokhatasurveyno(){
    String Villagenam=null; 
    int khatanu,surveyno;
   
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from khatasurveyconB";
            ResultSet rs=st.executeQuery(qr);
            CBsurveyno.removeAllItems();
            while(rs.next()){
            khatanu=rs.getInt("khatanum");
            surveyno=rs.getInt("surveynum");
            Villagenam=rs.getString("village");
            CBsurveyno.addItem(khatanu+"-"+Villagenam+"-"+surveyno);
            }
          cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
          }
}
     
     private void FillCombokhatasurveyold(int newsurveyno,String villagename){
    String Villagenam=null;
    String oldsurveyno;
    int khatanu,surveyno;
   
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from khatasurveyconB where surveynum='"+newsurveyno+"' AND Village='"+villagename+"'";
            ResultSet rs=st.executeQuery(qr);
            CBOLDSURVEY.removeAllItems();
            while(rs.next()){
            khatanu=rs.getInt("khatanum");
            surveyno=rs.getInt("surveynum");
            Villagenam=rs.getString("village");
            oldsurveyno=rs.getString("OLDSURVEYNO");
            CBOLDSURVEY.addItem(surveyno+"    ---->     "+oldsurveyno);
            }
          cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
          }
}
      private void FillMAPS(){
            File MAPSFOLDER=new File("C:\\DLRMAPS");
       String allmaps[]=MAPSFOLDER.list();
       for(int j=0;j<=allmaps.length-1;j++){
           VillageMAP.addItem(allmaps[j]);
       }
      }
    
   public void close(){
    setDefaultCloseOperation(Userdetail.DISPOSE_ON_CLOSE);
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHATADetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHATADetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHATADetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHATADetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHATADetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANYRORWEBSITE;
    private javax.swing.JComboBox<String> CBKhata;
    private javax.swing.JComboBox<String> CBOLDSURVEY;
    private javax.swing.JComboBox<String> CBsurveyno;
    private javax.swing.JButton GETOLD;
    private javax.swing.JComboBox<String> VillageMAP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField khatanum;
    private javax.swing.JTextField seleddrno;
    private javax.swing.JTextField village;
    // End of variables declaration//GEN-END:variables
}
