/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecthomeoracledb;

import io.netty.util.internal.StringUtil;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

/**
 *
 * @author Deval Nayak
 */
public class KHATADetailsIORA extends javax.swing.JFrame {
 WebDriver wb;
    /**
     * Creates new form KHATADetails
     */
    public KHATADetailsIORA() {
        initComponents();
        System.setProperty("webdriver.chrome.driver", "C:\\CHROMEDRIVERS\\chromedriver-win64_140\\chromedriver.exe");  
        FillCombokhata();
        FillCombokhatasurveyno();
        FillMAPS();
        FillComboIORA1();
        close();
        
        
        
       
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBKhata = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ANYRORWEBSITE = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CBsurveyno = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        VillageMAP = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CBIORA = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IORA DOWNLOADS");

        CBKhata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKhataActionPerformed(evt);
            }
        });

        jButton1.setText("GET 8A KHATA DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ANYRORWEBSITE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ANYRORWEBSITE.setText("IORA");
        ANYRORWEBSITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANYRORWEBSITEActionPerformed(evt);
            }
        });

        jButton3.setText("GET 7 DETAILS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("ALL KHATA SURVEY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        VillageMAP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VillageMAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VillageMAPActionPerformed(evt);
            }
        });

        jButton5.setText("OPEN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("OPENFOLDER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("GET 12");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBIORA, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(CBKhata, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(CBsurveyno, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ANYRORWEBSITE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                        .addGap(120, 120, 120))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VillageMAP, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(CBIORA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ANYRORWEBSITE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(VillageMAP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBKhata, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBsurveyno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      DBFunctionInterface dbij=new SearchData();
          String khata=CBKhata.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_ror_type"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(3);
         Thread.sleep(500);
       }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_district"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ddl_taluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ddl_village"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            Thread.sleep(500);
                   
           }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement khatano=wb.findElement(By.id("txt_ror_no"));
            khatano.sendKeys(ar[0]);
            Thread.sleep(500);
            wb.findElement(By.id("btn_add_ror")).click();
             Thread.sleep(1000);
           }catch(Exception e){
              System.out.println(e.getMessage());
         }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ANYRORWEBSITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANYRORWEBSITEActionPerformed
       wb=new ChromeDriver();   
        DBFunctionInterface dbij=new SearchData();
          String Slink=dbij.searchlink("IORA");
          String cont=CBIORA.getSelectedItem().toString().toUpperCase();
           DBFunctionInterface irs=new SearchData();
           String data=irs.searchuser(cont, 3);
           String ar[];
           ar=data.split("\\|");
           String khata=CBsurveyno.getSelectedItem().toString();
          String arr[];
          arr=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(arr[0]));
           
       try { 
    	 wb.navigate().to(Slink);
         Thread.sleep(2000);
         wb.findElement(By.id("txt_mobile_no")).sendKeys(ar[5]);
         int captcha = JOptionPane.showConfirmDialog(null, "confirm","Title of the panel", JOptionPane.OK_CANCEL_OPTION);
         wb.findElement(By.id("btn_generate_otp")).click();
         int captchb = JOptionPane.showConfirmDialog(null, "confirm","Title of the panel", JOptionPane.OK_CANCEL_OPTION);
         wb.findElement(By.id("btn_next")).click();
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }
      
      
//      try{
//          wb.findElement(By.id("ddl_district")).click();
//         WebElement district=wb.findElement(By.id("ddl_district"));        
//         Select districtdropdown=new Select(district);
//         districtdropdown.selectByIndex(25);
//         }catch(Exception e){
//          System.out.println(e.getMessage());
//      }
//      
//      try{
//          wb.findElement(By.id("ddl_taluka")).click();
//         WebElement taluka=wb.findElement(By.id("ddl_taluka"));
//         Select talukadropdown=new Select(taluka);
//         talukadropdown.selectByIndex(5);
//         }catch(Exception e){
//          System.out.println(e.getMessage());
//      }
//      
//      try{
//           WebElement Village=wb.findElement(By.id("ddl_Village"));
//            Select villagedropdown=new Select(Village);
//            villagedropdown.selectByIndex(seleniumddno);
//      }catch(Exception e){
//          System.out.println(e.getMessage());
//      }
//      
      
      
         
    }//GEN-LAST:event_ANYRORWEBSITEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         DBFunctionInterface dbij=new SearchData();
          String khata=CBKhata.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_ror_type"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(1);
         Thread.sleep(500);
       }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_district"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ddl_taluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ddl_village"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            Thread.sleep(500);
                   
           }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
           try{
           WebElement surveyno=wb.findElement(By.id("ddl_surveyno"));
            Select objsurvey=new Select(surveyno);
            String checksurveyno=CBsurveyno.getSelectedItem().toString();
            String arr[]=checksurveyno.split("-");
            int arlen=arr.length;
            String str=arr[arlen-1];
            objsurvey.selectByValue(str);
            Thread.sleep(500);  
            wb.findElement(By.id("btn_add_ror")).click();
            Thread.sleep(1000);
           }catch(Exception ex){
               System.out.println(ex.getMessage());
           }
         
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ALLKHATASURVEY aks=new ALLKHATASURVEY();
        aks.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VillageMAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VillageMAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VillageMAPActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Desktop desktop = Desktop.getDesktop();
       String Village=VillageMAP.getSelectedItem().toString();
       String DLRMAPS="C:\\DLRMAPS\\"+Village;
       File dirToOpen = null;
       try {
            dirToOpen = new File(DLRMAPS);
           try {
               desktop.open(dirToOpen);
           } catch (IOException ex) {
               Logger.getLogger(DocumentsFolders.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (IllegalArgumentException iae) {
            System.out.println("File Not Found");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CBKhataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKhataActionPerformed
//        String getkhata=CBKhata.getSelectedItem().toString();
//        String arr[]=getkhata.split("-");
//        FillCombokhatasurveyno(Integer.parseInt(arr[0])); 
    }//GEN-LAST:event_CBKhataActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Desktop desktop = Desktop.getDesktop();
       String DLRMAPS="C:\\DLRMAPS";
       File dirToOpen = null;
       try {
            dirToOpen = new File(DLRMAPS);
           try {
               desktop.open(dirToOpen);
           } catch (IOException ex) {
               Logger.getLogger(DocumentsFolders.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (IllegalArgumentException iae) {
            System.out.println("File Not Found");
        }        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           DBFunctionInterface dbij=new SearchData();
          String khata=CBKhata.getSelectedItem().toString();
          String ar[];
          ar=khata.split("-");
          int seleniumddno=dbij.searchkhatanoSELE(Integer.parseInt(ar[0]));
          
       try { 
    	 Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_ror_type"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(2);
         Thread.sleep(500);
       }
       catch(Exception e){
           System.out.println(e.getMessage());
       }    
          
       try { 
    	Thread.sleep(2000);
         WebElement district=wb.findElement(By.id("ddl_district"));        
         Select districtdropdown=new Select(district);
         districtdropdown.selectByIndex(25);
         Thread.sleep(500);
        }
       catch(Exception e){
           System.out.println(e.getMessage());
       }  
         try{
              WebElement taluka=wb.findElement(By.id("ddl_taluka"));
              Select talukadropdown=new Select(taluka);
              talukadropdown.selectByIndex(5);
              Thread.sleep(500);
         }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
         try{
            WebElement Village=wb.findElement(By.id("ddl_village"));
            Select villagedropdown=new Select(Village);
            villagedropdown.selectByIndex(seleniumddno);
            Thread.sleep(500);
                   
           }catch(Exception e){
              System.out.println(e.getMessage());
         }
         
           try{
           WebElement surveyno=wb.findElement(By.id("ddl_surveyno"));
            Select objsurvey=new Select(surveyno);
            String checksurveyno=CBsurveyno.getSelectedItem().toString();
            String arr[]=checksurveyno.split("-");
            int arlen=arr.length;
            String str=arr[arlen-1];
            objsurvey.selectByValue(str);
            Thread.sleep(500);  
            wb.findElement(By.id("btn_add_ror")).click();
            Thread.sleep(1000);
           }catch(Exception ex){
               System.out.println(ex.getMessage());
           }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void FillCombokhata(){
    String Villagenam=null; 
    int khatanu;
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from khatano";
            ResultSet rs=st.executeQuery(qr);
            CBKhata.removeAllItems();
            while(rs.next()){
            khatanu=rs.getInt("khatano");
            Villagenam=rs.getString("village");
            CBKhata.addItem(khatanu+"-"+Villagenam);
            }
          cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
         }
       
}
     private void FillCombokhatasurveyno(){
    String Villagenam=null; 
    int khatanu,surveyno;
   
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from khatasurveycon";
            ResultSet rs=st.executeQuery(qr);
            CBsurveyno.removeAllItems();
            while(rs.next()){
            khatanu=rs.getInt("khatano");
            surveyno=rs.getInt("surveyno");
            Villagenam=rs.getString("village");
            CBsurveyno.addItem(khatanu+"-"+Villagenam+"-"+surveyno);
            }
          cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
          }
}
      private void FillMAPS(){
            File MAPSFOLDER=new File("C:\\DLRMAPS");
       String allmaps[]=MAPSFOLDER.list();
       for(int j=0;j<=allmaps.length-1;j++){
           VillageMAP.addItem(allmaps[j]);
       }
      }
    
      
      
      
      
      private void FillComboIORA1(){
    String Id=null; 
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE","system","12345");
            Statement st=cn.createStatement();
            String qr="Select * from userdetail";
            ResultSet rs=st.executeQuery(qr);
            while(rs.next()){
            Id=rs.getString("UFNAME");
            CBIORA.addItem(Id);
            }
            cn.close();
         }   
        catch(Exception e){
            System.out.println(e.getMessage());
            
        }
      }
   public void close(){
    setDefaultCloseOperation(Userdetail.DISPOSE_ON_CLOSE);
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHATADetailsIORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHATADetailsIORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHATADetailsIORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHATADetailsIORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHATADetailsIORA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANYRORWEBSITE;
    private javax.swing.JComboBox<String> CBIORA;
    private javax.swing.JComboBox<String> CBKhata;
    private javax.swing.JComboBox<String> CBsurveyno;
    private javax.swing.JComboBox<String> VillageMAP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
